---

- name: Install EPEL repo
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  when: ansible_os_family == 'RedHat'
  tags:
    - repo-epel

- name: Import EPEL GPG key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: ansible_os_family == 'RedHat'
  tags:
    - repo-epel
